#!/usr/bin/env bash
# print domains and subdomains

print_domain_subdomain() {
    local query="$1"
    local subdomain="$2"
    local domain="$3"
    local output=$(dig "$query" | grep -A1 'ANSWER SECTION:')
    local record=$(echo "$output" | awk 'NR==2 {print $4}')
    local ip=$(echo "$output" | awk 'NR==2 {print $5}')
    printf "The subdomain %s is a %s record and points to %s\n" "$subdomain" "$record" "$ip"
}

if [ "$#" -eq 2 ]; then
    print_domain_subdomain "$2.$1" "$2" "$1"
else
    print_domain_subdomain "www.$1" "www" "$1"
    print_domain_subdomain "lb-01.$1" "lb-01" "$1"
    print_domain_subdomain "web-01.$1" "web-01" "$1"
    print_domain_subdomain "web-02.$1" "web-02" "$1"
fi
