#!/usr/bin/env bash
# Substitute values at indices 4, 9, and 17.

current_index=1

while [ $current_index -le 20 ]
do
  echo "$current_index"
  case $current_index in
	"4") echo "bad luck from China";;
	"9") echo "bad luck from Japan";;
	"17") echo "bad luck from Italy";;
  esac
(( current_index++ ))
done
